name: bookforest
description: A new Flutter project.
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter  



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  go_router: ^13.0.1
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  collection: ^1.17.0
  dio: ^5.1.2
  retrofit: ^4.0.1
  easy_debounce: ^2.0.3
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.2.0
  freezed_annotation: ^2.4.1
  logger: any
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  visibility_detector: ^0.4.0+2
  # firebase
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^16.1.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_performance: ^0.9.2+6
  ###
  kakao_flutter_sdk_user: ^1.5.0
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0
  card_swiper: ^3.0.1
  dropdown_button2: ^3.0.0-beta.7
  flutter_speed_dial: ^7.0.0
  kakao_map_plugin: ^0.2.2
  fl_chart: ^0.66.1
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.2
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.0
  mockito: ^5.4.0  



flutter:

  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/images/icon/
    - assets/images/login/
    - assets/app_icon/
    - .env

  fonts:
    - family: Inter
      fonts:
          - asset: assets/fonts/Inter-Thin.ttf
            weight: 100
          - asset: assets/fonts/Inter-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Inter-Light.ttf
            weight: 300
          - asset: assets/fonts/Inter-Regular.ttf
            weight: 400
          - asset: assets/fonts/Inter-Medium.ttf
            weight: 500
          - asset: assets/fonts/Inter-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Inter-Bold.ttf
            weight: 700
          - asset: assets/fonts/Inter-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Inter-Black.ttf
            weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app-icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21